# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasuntu', '0003_auto_20180314_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistpage',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
