# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glasuntu', '0005_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='social_media',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='glasuntu.VenuePage'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
        migrations.AddField(
            model_name='venuepage',
            name='genre',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='venuepage',
            name='info',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='venuepage',
            name='picture',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='venuepage',
            name='website',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='venuepage',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='venuepage',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
