# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-20 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasuntu', '0010_auto_20180320_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistpage',
            name='genre',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='artistpage',
            name='info',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='artistpage',
            name='picture',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='artistpage',
            name='website',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='artistpage',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
