# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-21 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasuntu', '0012_auto_20180321_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuepage',
            name='genre',
            field=models.CharField(default='', max_length=200),
        ),
    ]
