# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-21 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasuntu', '0014_auto_20180321_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=''),
        ),
    ]
